# Site settings
title: K&E Technology Consultants Ltd
email: info@ketech.org
description: "K&E Technology Consultants Ltd is a software technology consulting firm based in London, United Kingdom. We provide technology solutions to businesses and individuals."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: ketech-org

# Build settings
markdown: kramdown
